server:
  port: 8088
spring:
  datasource: # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: zhaoyujie
# 支付相关配置
pacee1:
  image:
    faceLocation: /file/image/foodie/faces
    serverUrl: http://api.enbuys.com:8088/foodie/faces/
  pay:
    returnUrl: http://api.enbuys.com:8088/orders/notifyMerchantOrderPaid